import { createApp } from "vue";
import App from "./App.vue";
import router from "./router";
import store from "./store";
import "@/assets/styles/tailwind.css";
import { library } from "@fortawesome/fontawesome-svg-core";
import { faPhone, faEnvelope } from "@fortawesome/free-solid-svg-icons";
import { faTwitter, faFacebookSquare, faLinkedin, faPinterestSquare, faVimeo} from "@fortawesome/free-brands-svg-icons";
library.add(faPhone, faEnvelope, faTwitter, faFacebookSquare, faLinkedin, faPinterestSquare, faVimeo);
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";
createApp(App).use(store).use(router).use(library).component("font-awesome-icon", FontAwesomeIcon).mount("#app");
